name = "Normalize"
uuid = "a3bd4e16-cdad-4d21-8f1a-18ddf87cde7f"
authors = ["muhadamanhuri <mredamanhuri@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ExcelFiles = "89b67f3b-d1aa-5f6f-9ca4-282e8d98620d"
SciPy = "ebc72ef8-9537-4fb0-b64e-ac76025fed2d"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
